### ISSUE TITLE
Add a pipeline manager

### ISSUE THREAD

**Issue by sionovd** [ItamarWilf/PipeRT#27]
We should consider adding some sort of a "master component" which would manage the pipeline. 

A few examples for how it could benefit us: 
- it would give us the ability to shut down the whole pipeline at once in the case of an error
- it could manage the zerorpc communication in a more organized way 
- it allows us to plug in/unplug certain components during runtime

**Comment by MayoG** [comment]
The way we are going to manage the pipeline:

One class called `PipelineManager` that contains Components.

Each Component will contain:
- Routines
- Queues - The way the routines communicate with each other

we decided to do this like this because: 
1. It makes the pipeline more dynamic at runtime
2. It makes it easier to maintain for the long term (survivability)
3. It makes it easier to add more routines without changing existing code(Open/Close principle, decoupling)

side notes:
- We will add a routines folder to contain all of the routines. each routine will have a separate file.
- We won't have any more premade components like (vid_capture, pose_estimation, face_detection...) except for unique ones like flask_display.

Questions / suggestions for improving are welcome :)
