### ISSUE TITLE
Fix demo_run

### ISSUE THREAD

**Issue by ItayHoresh** [ItamarWilf/PipeRT#31]
Fix all components.

**Comment by MayoG** [comment]
Components that need to be updated:
- [ ]  cv2_display
- [ ] canny
- [ ] DroneCapture
- [ ] FaceDetection
- [ ] PoseEstimation

**Comment by OmriKaduri** [comment]
Hi @ItayHoresh, can you ellaborate about the bug?

**Comment by ItayHoresh** [comment]
Hi @OmriKaduri, there are some bugs in the components that guy mentioned. In order to run the demo_run script we need to resolve them.
Some bugs are about the zerorpc server, dependencies and other..

**Comment by OmriKaduri** [comment]
Thanks for your answer. 
Yet I still think this issue isn't detailed enough. I understand that you guys speak to each other on a daily basis, but in order to be able to maintain an healthy development community in-sync on what's going on, our issues should be as informative as possible. Saying that "there are some bugs" gives no details about what this issue is about.

Therefore It would be nice to see some details about the bugs (how to reproduce, error messages) and the tests you think that should be written after solving them.  
:)

**Comment by ItayHoresh** [comment]
![Screenshot from 2020-03-04 10-29-01](https://user-images.githubusercontent.com/24764732/75860006-c6b6c100-5e03-11ea-9c34-d18c2c9c22a5.png)

The components aren't updated. Every component is trying to create the zerorpc server twice.
Creating the zerorpc server once will resolve the problem.

**Comment by ItayHoresh** [comment]
Non relevant anymore. From now on we will use the pipe manager to run components.
