### ISSUE TITLE
New design for running the pipeline

### ISSUE THREAD

**Issue by MayoG** [ItamarWilf/PipeRT#88]
![NewDisignForPipeline](https://user-images.githubusercontent.com/19624576/81497880-1618e200-92ca-11ea-89df-fec3970bc868.png)

**Some notes:**

- Each component will be run in a separate python process.

- The pipeline manager will communicate with the components using zeroRPC.

- The pipeline manager will no longer hold the component as an object, instead it will hold the zeroRPC port of the component.

- The [BaseComponent](https://github.com/ItamarWilf/PipeRT/blob/master/pipert/core/component.py) will be the template of a component and will get parameters for building its own routines and queues.

**Why the changes:**

There are a couple of issues with the current implementation of the `PipelineManager`:

1. GPU is only supported when the entire pipeline runs in a single `process`. 
The reason for this is quite invloved, and has to do with `CUDA` not being able to run on `forked sub-processes`. Details: https://pytorch.org/docs/master/notes/multiprocessing.html

The immediately obvious solution is to just use `spawn` as the starting method for new processes rather than the default `fork`. The issue with this is that Python uses `pickle` to transfer data from the parent process to the newly spawned sub-process. 

This raises a couple of issues:
- `Routine` is not serializable. By default it contains a `logger` and a thread-safe `Queue`, both not serializable. A workaround could be found to make the base `Routine` class serializable, but issues don't end there.
- Any concrete routine\component that uses CUDA will have to be designed with serialization in mind.
- Even assuming that everything is serializable, `pickle` has some issues with the way `PipelineManager` dynamically imports modules.

Even if all `pickle` related issues are solved, there is another problem:

2. The `PipelineManager` is too tightly coupled with everything.
With the current implementation, the manager must be used as it is the only entity able to build and  run any and all parts of the pipeline, making it impossible to separate components into different containers when eventually deploying at the edge.

**Workflow:**

1. The pipeline manager gets a config file.

2. The pipeline manager using the template (`BaseComponent`) file and activating it in a new python process.

3. While the pipeline manager activates the template, it sends the component's parameters from the configuration file (like queues and routines that are inside the component)

4. The new component (that inside the python process) opens a zeroRPC server for the pipeline manager to be able to communicate with him.

5. The pipeline manager will be able to control the component using the zeroRPC server when connecting to it as a client.

- With this setup using the manager is optional, as each component will be able to build and run itself provided a configuration file.

- When finally deployed, each component will inhabit its own container and a separate container can host the manager itself (to be able to control different components)

@sionovd @VladShtompel @ItayHoresh 
Make sure that i didn't miss anything and add if necessary

**Comment by VladShtompel** [comment]
Added clarification with regards to why these changes happen to the main post.
Would love to hear opinions and/or questions from @ItamarWilf @OmriKaduri

**Comment by OmriKaduri** [comment]
Wow, you've done some serious work there. I'll give a short response about the first concern that came up to mind while I read this right now, and hopefully will find the time tomorrow to do some more extensive reading and give a more detailed response (I'll have to dive deeper about all the `CUDA` problems with multiprocessing and the part about `pickle` problems).

When I think of the responsibilities (While trying to keep [SRP](https://en.wikipedia.org/wiki/Single-responsibility_principle) hold) of the `PipelineManager`, I can definitely identify:
1. Setup components (by configuration)
2. Control components while they're running (scaling, killing, logging, etc.?)

And the main concern I have after that thought is that I've essentially (roughly) detailed the responsibilities of a service orchestrator. I.e., In a container-based system deployed on K8s, I'll set the ConfigMap for each container and let the master know my preferences for deployment (scaling, logging, killing, etc...). In a linux-based system (with multiple services), I'll use [systemd](https://en.wikipedia.org/wiki/Systemd) in order to manage my processes. And there are many more examples of service orchestrators.

What do you think? I hope my intention was clear - I think you've done some amazing work that made us UNDERSTAND what do we actually need in order to efficiently manage our pipeline. Now we need to find the best tool for the job.

**Comment by ItayHoresh** [comment]
> What do you think? I hope my intention was clear - I think you've done some amazing work that made us UNDERSTAND what do we actually need in order to efficiently manage our pipeline. Now we need to find the best tool for the job.

I totally agree with you. In my opinion, the most important thing is that we more and less know what we want from the pipe manager.

> * Setup components (by configuration)
> * Control components while they're running (scaling, killing, logging, etc.?)

And this is why the pipe manager can be optional. It will be easy to deploy both on a linux-based system and container-based system deployed on K8s.

**Comment by ItamarWilf** [comment]
First of all, fix the drawing, it's horrible :)
